---

- name: Install postfix
  apt: name=postfix state=present
  notify:
  - start postfix
  - enabled postfix

- name: Copy configuration to the machine
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
     - { src: "main.cf.j2", dest: "/etc/postfix/main.cf" }
  notify: reload postfix
